<?

/* @var $model Foomo\Log\Plot\Plotter */

$timeWindowInSecs = $model->lastRequest - $model->firstRequest;

if($timeWindowInSecs * 10 > 40000) {
	$width = 40000;
} else {
	$width = $timeWindowInSecs * 10;
}

?>
# autogenerated plot
set term png truecolor size <?= $width ?>, 1600
set output "report<? // ' -' . date('y-m-d-H-i-s')?>.png"

set xdata time

set timefmt "%s"
#set xdata time
#set yrange[0.0001:10]

set style fill solid 1.0 noborder

